---
title: "rendo"
author: "dnanto"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    toc_depth: 1
params:
  path1: "kajon.fna"
  path2: "enzymes.tsv"
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  echo = FALSE,
	warning = FALSE,
	message = FALSE,
	fig.align = "center",
	fig.width = 10,
	fig.height = 10
)
options(
	knitr.kable.NA = ""
)
if (!exists("PATH"))
{
	PATH = system('source ~/.bash_profile && echo "$PATH"', intern = T)
	Sys.setenv(PATH = PATH)
}
```

```{r}
system(paste("rendo.py", params$path1, params$path2, "2>", "/dev/null", collapse = " "), intern = T) %>%
  read_tsv() %>%
  mutate(Kbp = (r5 + r3) / 1000 / 2) %>%
  count(id, enzyme, Kbp) %>%
  ggplot(aes(Kbp, id, fill = n)) +
    geom_tile(width = 50 / 1000 / 2) +
    scale_fill_continuous(na.value = "transparent") +
    facet_wrap(enzyme ~ ., ncol = 1, strip.position = "right") +
    theme_minimal() +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      legend.position = "bottom"
    )
```
